In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 5])

In [3]:
x

array([1, 2, 3, 5])

In [4]:
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [13]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

In [15]:
np.vander(x, increasing=False)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [39]:
np.vander(x, N=5, increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   5,  25, 125, 625]])

In [21]:
np.vander(x, N=5, increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [625, 125,  25,   5,   1]])

In [43]:
np.vander(x, N=5, increasing=True)[:,1:]

array([[  1,   1,   1,   1],
       [  2,   4,   8,  16],
       [  3,   9,  27,  81],
       [  5,  25, 125, 625]])

In [44]:
np.vander(x, N=5, increasing=False)[:,:-1]

array([[  1,   1,   1,   1],
       [ 16,   8,   4,   2],
       [ 81,  27,   9,   3],
       [625, 125,  25,   5]])